title: Memo, please # name of the site
author: jwpark # name of site's author
email: jiwoop.jj@gmail.com # email of site's author
url: https://riggraz.dev/no-style-please # root address of the site
description: > # description of the site (multiple lines allowed)
  A (nearly) no-CSS, fast, minimalist Jekyll theme.

permalink: /:slug.html

favicon: "./logo.png" # relative path to site's favicon
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental : false